name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        # Using the exact system path solves the folder error
        working-directory: /home/ubuntu/Final-Project

      - name: Run tests
        run: npm test
        working-directory: /home/ubuntu/Final-Project

      - name: Restart application with PM2
        if: success()
        run: pm2 restart employee-system
        working-directory: /home/ubuntu/Final-Project
